### PR TITLE
Add HPA options to async samples

### PR DESCRIPTION
**Pull request by benjaminhuo**
Signed-off-by: Benjamin Huo <benjamin@kubesphere.io>

### CODE REVIEW

**Review by tpiperatgod — APPROVED** [review]

**Comment by benjaminhuo** [comment]
@Felixnoo @FeynmanZhou , please help to udpate the website according to the latest update in this PR
For example https://openfunction.dev/docs/best-practices/interact-with-dapr-output-binding/

**Comment by FeynmanZhou** [comment]
> @Felixnoo @FeynmanZhou , please help to udpate the website according to the latest update in this PR For example https://openfunction.dev/docs/best-practices/interact-with-dapr-output-binding/

Sure, I created a label for those PRs that required the doc updates. We could add this label for any PR/issue in the future.

**Comment by Felixnoo** [comment]
> @Felixnoo @FeynmanZhou , please help to udpate the website according to the latest update in this PR For example https://openfunction.dev/docs/best-practices/interact-with-dapr-output-binding/

OK.

**Comment by benjaminhuo** [comment]
@Felixnoo I'll update this PR in another PR, you can merge the new PR soon

**Pull request merged**
