### PR TITLE
Add OpenFunction katacoda scenarios

### PR DESCRIPTION
**Pull request by x893675**
Signed-off-by: x893675 <x893675@icloud.com>

[OpenFunction Issue#167](https://github.com/OpenFunction/OpenFunction/issues/167) 

[Preview OpenFunction Scenario](https://www.katacoda.com/x893675)

### CODE REVIEW

**Review by tpiperatgod — COMMENTED** [review]
Many thanks to @x893675 !

I validated this scenario on Katacode and the results met our expectations, that is, demonstrating the installation process of OpenFunction on Kubernetes.

However, there is a small problem, the following step causes an exception (it seems doesn't really matter)

image
```shell
controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
Warning: Permanently added 'node01,172.17.0.53' (ECDSA) to the list of known hosts.
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
Reading package lists...
Building dependency tree...
Reading state information...
kubectl is already the newest version (1.19.0-00).
kubelet is already the newest version (1.19.0-00).
The following packages were automatically installed and are no longer required:
  libc-ares2 libhttp-parser2.7.1 libnetplan0 libuv1 nodejs-doc
  python3-netifaces
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
```

**Comment by x893675** [comment]
> Many thanks to @x893675 !
> 
> I validated this scenario on Katacode and the results met our expectations, that is, demonstrating the installation process of OpenFunction on Kubernetes.
> 
> However, there is a small problem, the following step causes an exception (it seems doesn't really matter)
> 
> image
> 
> ```shell
> controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
> Warning: Permanently added 'node01,172.17.0.53' (ECDSA) to the list of known hosts.
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> controlplane $ ssh node01 "apt-get install -y kubelet=1.19.0-00 kubectl=1.19.0-00"
> Reading package lists...
> Building dependency tree...
> Reading state information...
> kubectl is already the newest version (1.19.0-00).
> kubelet is already the newest version (1.19.0-00).
> The following packages were automatically installed and are no longer required:
>   libc-ares2 libhttp-parser2.7.1 libnetplan0 libuv1 nodejs-doc
>   python3-netifaces
> Use 'apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 199 not upgraded.
> ```

@tpiperatgod  
It really doesn't matter.  I think the cause of this problem is not this command.
And I verified it many times and found that this problem does not occur 100% .

**Comment by benjaminhuo** [comment]
@x893675 @tpiperatgod there is a fix for this
https://askubuntu.com/questions/1109982/e-could-not-get-lock-var-lib-dpkg-lock-frontend-open-11-resource-temporari

**Review by tpiperatgod — APPROVED** [review]

**Comment by x893675** [comment]
@benjaminhuo @tpiperatgod 

Add additional explanation for step4

QQ20211129-094705@2x

**Comment by tpiperatgod** [comment]
Approved

**Review by benjaminhuo — APPROVED** [review]

**Comment by benjaminhuo** [comment]
Thanks for the contribution, It'll be great if more function sample demos can be added @x893675

**Pull request merged**
